cask_args appdir: '/Applications', caskroom: '~/.dotfiles/cask'

tap 'homebrew/versions'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'clang-format'
brew 'cmake'
brew 'ctags'
brew 'go'
brew 'htop'
brew 'hub'
brew 'pstree'
brew 'reattach-to-user-namespace'
brew 'tmux'
brew 'vim'

cask '1password'
cask 'alfred'
cask 'coderunner'
cask 'dropbox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'hopper-disassembler'
cask 'iterm2-beta'
cask 'sourcetree'
cask 'suspicious-package'
cask 'the-unarchiver'
