#!/usr/bin/env python3
"""Generate plain.toml from fancy.toml: no Nerd Font glyphs, no background bar.

Re-run after editing fancy.toml. ~/.zshrc picks plain.toml unless the terminal
is one known to have a Nerd Font.
"""
import re
from pathlib import Path

SRC = Path(__file__).with_name("fancy.toml")
DST = Path(__file__).with_name("plain.toml")
# Nerd Font glyphs live in the BMP Private Use Area plus planes 15-16.
PUA = re.compile(f"[{chr(0xE000)}-{chr(0xF8FF)}{chr(0xF0000)}-{chr(0xFFFFD)}]")
QUOTED = re.compile(r"'[^'\n]*'|\"[^\"\n]*\"")
# Bar decoration: the round caps (now empty) and the padding cell before them.
BLANK_MARKUP = re.compile(r"^\[\s*\]\([^)]*\)\\?\n", re.M)
BACKGROUND = re.compile(r" ?\bbg:[\w#]+")
ASCII_FOR = {"❯": ">", "❮": "<", "…": "..."}

out = PUA.sub("", SRC.read_text(encoding="utf-8"))
for fancy, plain in ASCII_FOR.items():
    out = out.replace(fancy, plain)
out = BLANK_MARKUP.sub("", out)
out = BACKGROUND.sub("", out)
# Every $symbol is either emptied above or falls back to a glyph starship supplies
# itself (battery, conda), so drop the field rather than render a blank or a box.
out = out.replace("$symbol", "")
# That leaves doubled spaces behind ("  $branch"), and it also tightens fancy's
# roomier two-space segment gaps to one - which is what we want without the bar.
out = QUOTED.sub(lambda m: re.sub(" {2,}", " ", m.group(0)), out)
# An emptied symbol just renders nothing, but an emptied path substitution would
# replace the directory name with blanks - drop those lines instead.
lines, table = [], ""
for line in out.splitlines(keepends=True):
    if line.startswith("["):
        table = line.strip()
    if table == "[directory.substitutions]" and re.fullmatch(
        r'\s*"[^"]+"\s*=\s*"\s*"\s*\n?', line
    ):
        continue
    lines.append(line)

DST.write_text(
    "# Generated by gen-plain.py from fancy.toml - do not edit.\n" + "".join(lines),
    encoding="utf-8",
)
written = DST.read_text(encoding="utf-8")
bad = sorted({c for c in written if not c.isascii()})
assert not bad, f"non-ascii survived: {bad} - add it to ASCII_FOR"
assert "bg:" not in written, "background survived"
print(f"wrote {DST}")
